"""init db

Revision ID: 262f2d3f7998
Revises: 80b5d6291542
Create Date: 2018-01-18 08:01:23.205127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262f2d3f7998'
down_revision = '80b5d6291542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobseeker', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobseeker', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobseeker', type_='foreignkey')
    op.drop_column('jobseeker', 'user_id')
    # ### end Alembic commands ###
