"""default

Revision ID: 7f8305c65e18
Revises: 78f86b98966f
Create Date: 2018-01-26 09:36:53.904144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f8305c65e18'
down_revision = '78f86b98966f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('company', 'upodate_at')
    op.add_column('delivery', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('delivery', 'upodate_at')
    op.add_column('job_detail', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('job_detail', 'upodate_at')
    op.add_column('jobseeker', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('jobseeker', 'upodate_at')
    op.add_column('user', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'upodate_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upodate_at', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'update_at')
    op.add_column('jobseeker', sa.Column('upodate_at', mysql.DATETIME(), nullable=True))
    op.drop_column('jobseeker', 'update_at')
    op.add_column('job_detail', sa.Column('upodate_at', mysql.DATETIME(), nullable=True))
    op.drop_column('job_detail', 'update_at')
    op.add_column('delivery', sa.Column('upodate_at', mysql.DATETIME(), nullable=True))
    op.drop_column('delivery', 'update_at')
    op.add_column('company', sa.Column('upodate_at', mysql.DATETIME(), nullable=True))
    op.drop_column('company', 'update_at')
    # ### end Alembic commands ###
