"""init db

Revision ID: 80b5d6291542
Revises: 
Create Date: 2018-01-18 07:58:48.601523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b5d6291542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobseeker',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('upodate_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seekername', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('resume_up', sa.String(length=32), nullable=True),
    sa.Column('resumeId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resumeId')
    )
    op.create_table('user',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('upodate_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('cellphone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('upodate_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=64), nullable=True),
    sa.Column('num', sa.String(length=32), nullable=True),
    sa.Column('logo', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_companyname'), 'company', ['companyname'], unique=True)
    op.create_table('experience',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('upodate_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ep_id', sa.Integer(), nullable=True),
    sa.Column('desc_edu', sa.String(length=256), nullable=True),
    sa.Column('desc_job', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['ep_id'], ['jobseeker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_detail',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('upodate_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('jobname', sa.String(length=64), nullable=True),
    sa.Column('salary', sa.String(length=32), nullable=False),
    sa.Column('workaddress', sa.String(length=64), nullable=True),
    sa.Column('education', sa.String(length=32), nullable=True),
    sa.Column('release_time', sa.String(length=64), nullable=True),
    sa.Column('experience', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_detail.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('job_detail')
    op.drop_table('experience')
    op.drop_index(op.f('ix_company_companyname'), table_name='company')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('jobseeker')
    # ### end Alembic commands ###
