"""update again

Revision ID: b791c55147ba
Revises: 4cf1851e669d
Create Date: 2018-02-03 16:22:25.563182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b791c55147ba'
down_revision = '4cf1851e669d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_disable')
    # ### end Alembic commands ###
