"""add is valid

Revision ID: bfb6f9049a41
Revises: 27cb080a5612
Create Date: 2018-01-24 08:28:21.464440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb6f9049a41'
down_revision = '27cb080a5612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('isValid', sa.Boolean(), nullable=True))
    op.add_column('job_detail', sa.Column('isValid', sa.Boolean(), nullable=True))
    op.add_column('jobseeker', sa.Column('isValid', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isValid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isValid')
    op.drop_column('jobseeker', 'isValid')
    op.drop_column('job_detail', 'isValid')
    op.drop_column('company', 'isValid')
    # ### end Alembic commands ###
